// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cloud.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

enum Cloud_CloudConfigStatus: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case success // = 0
    case invalidParam // = 1
    case invalidState // = 2
    case UNRECOGNIZED(Int)

    init() {
        self = .success
    }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .success
        case 1: self = .invalidParam
        case 2: self = .invalidState
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .success: return 0
        case .invalidParam: return 1
        case .invalidState: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }
}

#if swift(>=4.2)

    extension Cloud_CloudConfigStatus: CaseIterable {
        // The compiler won't synthesize support with the UNRECOGNIZED case.
        static var allCases: [Cloud_CloudConfigStatus] = [
            .success,
            .invalidParam,
            .invalidState,
        ]
    }

#endif // swift(>=4.2)

enum Cloud_CloudConfigMsgType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case typeCmdGetSetDetails // = 0
    case typeRespGetSetDetails // = 1
    case UNRECOGNIZED(Int)

    init() {
        self = .typeCmdGetSetDetails
    }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .typeCmdGetSetDetails
        case 1: self = .typeRespGetSetDetails
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .typeCmdGetSetDetails: return 0
        case .typeRespGetSetDetails: return 1
        case let .UNRECOGNIZED(i): return i
        }
    }
}

#if swift(>=4.2)

    extension Cloud_CloudConfigMsgType: CaseIterable {
        // The compiler won't synthesize support with the UNRECOGNIZED case.
        static var allCases: [Cloud_CloudConfigMsgType] = [
            .typeCmdGetSetDetails,
            .typeRespGetSetDetails,
        ]
    }

#endif // swift(>=4.2)

struct Cloud_CmdGetSetDetails {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var userID = String()

    var secretKey = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Cloud_RespGetSetDetails {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var status: Cloud_CloudConfigStatus = .success

    var deviceSecret = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Cloud_CloudConfigPayload {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var msg: Cloud_CloudConfigMsgType {
        get { return _storage._msg }
        set { _uniqueStorage()._msg = newValue }
    }

    var payload: OneOf_Payload? {
        get { return _storage._payload }
        set { _uniqueStorage()._payload = newValue }
    }

    var cmdGetSetDetails: Cloud_CmdGetSetDetails {
        get {
            if case let .cmdGetSetDetails(v)? = _storage._payload { return v }
            return Cloud_CmdGetSetDetails()
        }
        set { _uniqueStorage()._payload = .cmdGetSetDetails(newValue) }
    }

    var respGetSetDetails: Cloud_RespGetSetDetails {
        get {
            if case let .respGetSetDetails(v)? = _storage._payload { return v }
            return Cloud_RespGetSetDetails()
        }
        set { _uniqueStorage()._payload = .respGetSetDetails(newValue) }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Payload: Equatable {
        case cmdGetSetDetails(Cloud_CmdGetSetDetails)
        case respGetSetDetails(Cloud_RespGetSetDetails)

        #if !swift(>=4.1)
            static func == (lhs: Cloud_CloudConfigPayload.OneOf_Payload, rhs: Cloud_CloudConfigPayload.OneOf_Payload) -> Bool {
                switch (lhs, rhs) {
                case let (.cmdGetSetDetails(l), .cmdGetSetDetails(r)): return l == r
                case let (.respGetSetDetails(l), .respGetSetDetails(r)): return l == r
                default: return false
                }
            }
        #endif
    }

    init() {}

    private var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "cloud"

extension Cloud_CloudConfigStatus: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "Success"),
        1: .same(proto: "InvalidParam"),
        2: .same(proto: "InvalidState"),
    ]
}

extension Cloud_CloudConfigMsgType: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "TypeCmdGetSetDetails"),
        1: .same(proto: "TypeRespGetSetDetails"),
    ]
}

extension Cloud_CmdGetSetDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CmdGetSetDetails"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "UserID"),
        2: .same(proto: "SecretKey"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &userID)
            case 2: try decoder.decodeSingularStringField(value: &secretKey)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !userID.isEmpty {
            try visitor.visitSingularStringField(value: userID, fieldNumber: 1)
        }
        if !secretKey.isEmpty {
            try visitor.visitSingularStringField(value: secretKey, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Cloud_CmdGetSetDetails, rhs: Cloud_CmdGetSetDetails) -> Bool {
        if lhs.userID != rhs.userID { return false }
        if lhs.secretKey != rhs.secretKey { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Cloud_RespGetSetDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".RespGetSetDetails"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "Status"),
        2: .same(proto: "DeviceSecret"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &status)
            case 2: try decoder.decodeSingularStringField(value: &deviceSecret)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if status != .success {
            try visitor.visitSingularEnumField(value: status, fieldNumber: 1)
        }
        if !deviceSecret.isEmpty {
            try visitor.visitSingularStringField(value: deviceSecret, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Cloud_RespGetSetDetails, rhs: Cloud_RespGetSetDetails) -> Bool {
        if lhs.status != rhs.status { return false }
        if lhs.deviceSecret != rhs.deviceSecret { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Cloud_CloudConfigPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CloudConfigPayload"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "msg"),
        10: .standard(proto: "cmd_get_set_details"),
        11: .standard(proto: "resp_get_set_details"),
    ]

    fileprivate class _StorageClass {
        var _msg: Cloud_CloudConfigMsgType = .typeCmdGetSetDetails
        var _payload: Cloud_CloudConfigPayload.OneOf_Payload?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            _msg = source._msg
            _payload = source._payload
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularEnumField(value: &_storage._msg)
                case 10:
                    var v: Cloud_CmdGetSetDetails?
                    if let current = _storage._payload {
                        try decoder.handleConflictingOneOf()
                        if case let .cmdGetSetDetails(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v { _storage._payload = .cmdGetSetDetails(v) }
                case 11:
                    var v: Cloud_RespGetSetDetails?
                    if let current = _storage._payload {
                        try decoder.handleConflictingOneOf()
                        if case let .respGetSetDetails(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v { _storage._payload = .respGetSetDetails(v) }
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            if _storage._msg != .typeCmdGetSetDetails {
                try visitor.visitSingularEnumField(value: _storage._msg, fieldNumber: 1)
            }
            switch _storage._payload {
            case let .cmdGetSetDetails(v)?:
                try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
            case let .respGetSetDetails(v)?:
                try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
            case nil: break
            }
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Cloud_CloudConfigPayload, rhs: Cloud_CloudConfigPayload) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._msg != rhs_storage._msg { return false }
                if _storage._payload != rhs_storage._payload { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
